# print("hello world")
word = "Manisha is good"
# print(word)
# print(word + " is a bad girl.")
# print(word.lower())
# print(word.islower())
# print(word.upper())
# print(word.isupper())
# print(word.upper().islower())
# print(len(word))
# print(word[0])
# print(word[6])
# print(word.index("i"))
print(word.replace("Manisha","Anu"))
print(word.replace("good","humble"))
